// AUTO-GENERATED by scripts/generate-stickers.mjs — do not edit by hand.
export interface StickerCategory { id: string; label: string; th: string; emoji: string }
export interface StickerDef { id: string; category: string; name: string; file: string; keywords: string[] }

export const STICKER_CATEGORIES: StickerCategory[] = [
  {
    "id": "hearts",
    "label": "Hearts",
    "th": "หัวใจ",
    "emoji": "❤️"
  },
  {
    "id": "flowers",
    "label": "Flowers",
    "th": "ดอกไม้",
    "emoji": "🌸"
  },
  {
    "id": "nature",
    "label": "Nature",
    "th": "ธรรมชาติ",
    "emoji": "🌳"
  },
  {
    "id": "stars",
    "label": "Stars",
    "th": "ดวงดาว",
    "emoji": "⭐"
  },
  {
    "id": "clouds",
    "label": "Clouds",
    "th": "เมฆ",
    "emoji": "☁️"
  },
  {
    "id": "birthday",
    "label": "Birthday",
    "th": "วันเกิด",
    "emoji": "🎂"
  },
  {
    "id": "baby",
    "label": "Baby",
    "th": "เด็กน้อย",
    "emoji": "👶"
  },
  {
    "id": "pets",
    "label": "Pets",
    "th": "สัตว์เลี้ยง",
    "emoji": "🐶"
  },
  {
    "id": "christmas",
    "label": "Christmas",
    "th": "คริสต์มาส",
    "emoji": "🎄"
  },
  {
    "id": "celebration",
    "label": "Celebration",
    "th": "เฉลิมฉลอง",
    "emoji": "🎉"
  },
  {
    "id": "travel",
    "label": "Travel",
    "th": "ท่องเที่ยว",
    "emoji": "✈️"
  },
  {
    "id": "summer",
    "label": "Summer",
    "th": "ฤดูร้อน",
    "emoji": "🏖️"
  },
  {
    "id": "school",
    "label": "School",
    "th": "โรงเรียน",
    "emoji": "🏫"
  },
  {
    "id": "wedding",
    "label": "Wedding",
    "th": "งานแต่ง",
    "emoji": "💍"
  },
  {
    "id": "cartoon",
    "label": "Cartoon",
    "th": "การ์ตูน",
    "emoji": "🎨"
  },
  {
    "id": "food",
    "label": "Food",
    "th": "อาหาร",
    "emoji": "🍓"
  },
  {
    "id": "vehicles",
    "label": "Vehicles",
    "th": "ยานพาหนะ",
    "emoji": "🚗"
  },
  {
    "id": "sports",
    "label": "Sports",
    "th": "กีฬา",
    "emoji": "⚽"
  },
  {
    "id": "cute",
    "label": "Cute",
    "th": "น่ารัก",
    "emoji": "🌈"
  },
  {
    "id": "misc",
    "label": "Miscellaneous",
    "th": "อื่นๆ",
    "emoji": "🎁"
  }
];

export const STICKERS: StickerDef[] = [
  {
    "id": "hearts-01",
    "category": "hearts",
    "name": "heart-01",
    "file": "/stickers/hearts/heart-01.svg",
    "keywords": [
      "hearts",
      "hearts",
      "หัวใจ",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "hearts-02",
    "category": "hearts",
    "name": "heart-02",
    "file": "/stickers/hearts/heart-02.svg",
    "keywords": [
      "hearts",
      "hearts",
      "หัวใจ",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "hearts-03",
    "category": "hearts",
    "name": "heart-03",
    "file": "/stickers/hearts/heart-03.svg",
    "keywords": [
      "hearts",
      "hearts",
      "หัวใจ",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "hearts-04",
    "category": "hearts",
    "name": "heart-04",
    "file": "/stickers/hearts/heart-04.svg",
    "keywords": [
      "hearts",
      "hearts",
      "หัวใจ",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "hearts-05",
    "category": "hearts",
    "name": "heart-05",
    "file": "/stickers/hearts/heart-05.svg",
    "keywords": [
      "hearts",
      "hearts",
      "หัวใจ",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "hearts-06",
    "category": "hearts",
    "name": "heart-06",
    "file": "/stickers/hearts/heart-06.svg",
    "keywords": [
      "hearts",
      "hearts",
      "หัวใจ",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "hearts-07",
    "category": "hearts",
    "name": "heart-07",
    "file": "/stickers/hearts/heart-07.svg",
    "keywords": [
      "hearts",
      "hearts",
      "หัวใจ",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "hearts-08",
    "category": "hearts",
    "name": "heart-08",
    "file": "/stickers/hearts/heart-08.svg",
    "keywords": [
      "hearts",
      "hearts",
      "หัวใจ",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "hearts-09",
    "category": "hearts",
    "name": "heart-09",
    "file": "/stickers/hearts/heart-09.svg",
    "keywords": [
      "hearts",
      "hearts",
      "หัวใจ",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "hearts-10",
    "category": "hearts",
    "name": "heart-10",
    "file": "/stickers/hearts/heart-10.svg",
    "keywords": [
      "hearts",
      "hearts",
      "หัวใจ",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "hearts-11",
    "category": "hearts",
    "name": "heart-11",
    "file": "/stickers/hearts/heart-11.svg",
    "keywords": [
      "hearts",
      "hearts",
      "หัวใจ",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "hearts-12",
    "category": "hearts",
    "name": "heart-12",
    "file": "/stickers/hearts/heart-12.svg",
    "keywords": [
      "hearts",
      "hearts",
      "หัวใจ",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "flowers-01",
    "category": "flowers",
    "name": "flower-01",
    "file": "/stickers/flowers/flower-01.svg",
    "keywords": [
      "flowers",
      "flowers",
      "ดอกไม้",
      "flower",
      "ดอกไม้"
    ]
  },
  {
    "id": "flowers-02",
    "category": "flowers",
    "name": "tulip-02",
    "file": "/stickers/flowers/tulip-02.svg",
    "keywords": [
      "flowers",
      "flowers",
      "ดอกไม้",
      "tulip",
      "ทิวลิป",
      "flower"
    ]
  },
  {
    "id": "flowers-03",
    "category": "flowers",
    "name": "flower-03",
    "file": "/stickers/flowers/flower-03.svg",
    "keywords": [
      "flowers",
      "flowers",
      "ดอกไม้",
      "flower",
      "ดอกไม้"
    ]
  },
  {
    "id": "flowers-04",
    "category": "flowers",
    "name": "tulip-04",
    "file": "/stickers/flowers/tulip-04.svg",
    "keywords": [
      "flowers",
      "flowers",
      "ดอกไม้",
      "tulip",
      "ทิวลิป",
      "flower"
    ]
  },
  {
    "id": "flowers-05",
    "category": "flowers",
    "name": "flower-05",
    "file": "/stickers/flowers/flower-05.svg",
    "keywords": [
      "flowers",
      "flowers",
      "ดอกไม้",
      "flower",
      "ดอกไม้"
    ]
  },
  {
    "id": "flowers-06",
    "category": "flowers",
    "name": "tulip-06",
    "file": "/stickers/flowers/tulip-06.svg",
    "keywords": [
      "flowers",
      "flowers",
      "ดอกไม้",
      "tulip",
      "ทิวลิป",
      "flower"
    ]
  },
  {
    "id": "flowers-07",
    "category": "flowers",
    "name": "flower-07",
    "file": "/stickers/flowers/flower-07.svg",
    "keywords": [
      "flowers",
      "flowers",
      "ดอกไม้",
      "flower",
      "ดอกไม้"
    ]
  },
  {
    "id": "flowers-08",
    "category": "flowers",
    "name": "tulip-08",
    "file": "/stickers/flowers/tulip-08.svg",
    "keywords": [
      "flowers",
      "flowers",
      "ดอกไม้",
      "tulip",
      "ทิวลิป",
      "flower"
    ]
  },
  {
    "id": "flowers-09",
    "category": "flowers",
    "name": "flower-09",
    "file": "/stickers/flowers/flower-09.svg",
    "keywords": [
      "flowers",
      "flowers",
      "ดอกไม้",
      "flower",
      "ดอกไม้"
    ]
  },
  {
    "id": "flowers-10",
    "category": "flowers",
    "name": "tulip-10",
    "file": "/stickers/flowers/tulip-10.svg",
    "keywords": [
      "flowers",
      "flowers",
      "ดอกไม้",
      "tulip",
      "ทิวลิป",
      "flower"
    ]
  },
  {
    "id": "flowers-11",
    "category": "flowers",
    "name": "flower-11",
    "file": "/stickers/flowers/flower-11.svg",
    "keywords": [
      "flowers",
      "flowers",
      "ดอกไม้",
      "flower",
      "ดอกไม้"
    ]
  },
  {
    "id": "flowers-12",
    "category": "flowers",
    "name": "tulip-12",
    "file": "/stickers/flowers/tulip-12.svg",
    "keywords": [
      "flowers",
      "flowers",
      "ดอกไม้",
      "tulip",
      "ทิวลิป",
      "flower"
    ]
  },
  {
    "id": "nature-01",
    "category": "nature",
    "name": "leaf-01",
    "file": "/stickers/nature/leaf-01.svg",
    "keywords": [
      "nature",
      "nature",
      "ธรรมชาติ",
      "leaf",
      "ใบไม้"
    ]
  },
  {
    "id": "nature-02",
    "category": "nature",
    "name": "tree-02",
    "file": "/stickers/nature/tree-02.svg",
    "keywords": [
      "nature",
      "nature",
      "ธรรมชาติ",
      "tree",
      "ต้นไม้",
      "pine"
    ]
  },
  {
    "id": "nature-03",
    "category": "nature",
    "name": "leaf-03",
    "file": "/stickers/nature/leaf-03.svg",
    "keywords": [
      "nature",
      "nature",
      "ธรรมชาติ",
      "leaf",
      "ใบไม้"
    ]
  },
  {
    "id": "nature-04",
    "category": "nature",
    "name": "tree-04",
    "file": "/stickers/nature/tree-04.svg",
    "keywords": [
      "nature",
      "nature",
      "ธรรมชาติ",
      "tree",
      "ต้นไม้",
      "pine"
    ]
  },
  {
    "id": "nature-05",
    "category": "nature",
    "name": "leaf-05",
    "file": "/stickers/nature/leaf-05.svg",
    "keywords": [
      "nature",
      "nature",
      "ธรรมชาติ",
      "leaf",
      "ใบไม้"
    ]
  },
  {
    "id": "nature-06",
    "category": "nature",
    "name": "tree-06",
    "file": "/stickers/nature/tree-06.svg",
    "keywords": [
      "nature",
      "nature",
      "ธรรมชาติ",
      "tree",
      "ต้นไม้",
      "pine"
    ]
  },
  {
    "id": "nature-07",
    "category": "nature",
    "name": "leaf-07",
    "file": "/stickers/nature/leaf-07.svg",
    "keywords": [
      "nature",
      "nature",
      "ธรรมชาติ",
      "leaf",
      "ใบไม้"
    ]
  },
  {
    "id": "nature-08",
    "category": "nature",
    "name": "tree-08",
    "file": "/stickers/nature/tree-08.svg",
    "keywords": [
      "nature",
      "nature",
      "ธรรมชาติ",
      "tree",
      "ต้นไม้",
      "pine"
    ]
  },
  {
    "id": "nature-09",
    "category": "nature",
    "name": "leaf-09",
    "file": "/stickers/nature/leaf-09.svg",
    "keywords": [
      "nature",
      "nature",
      "ธรรมชาติ",
      "leaf",
      "ใบไม้"
    ]
  },
  {
    "id": "nature-10",
    "category": "nature",
    "name": "tree-10",
    "file": "/stickers/nature/tree-10.svg",
    "keywords": [
      "nature",
      "nature",
      "ธรรมชาติ",
      "tree",
      "ต้นไม้",
      "pine"
    ]
  },
  {
    "id": "nature-11",
    "category": "nature",
    "name": "leaf-11",
    "file": "/stickers/nature/leaf-11.svg",
    "keywords": [
      "nature",
      "nature",
      "ธรรมชาติ",
      "leaf",
      "ใบไม้"
    ]
  },
  {
    "id": "nature-12",
    "category": "nature",
    "name": "tree-12",
    "file": "/stickers/nature/tree-12.svg",
    "keywords": [
      "nature",
      "nature",
      "ธรรมชาติ",
      "tree",
      "ต้นไม้",
      "pine"
    ]
  },
  {
    "id": "stars-01",
    "category": "stars",
    "name": "star-01",
    "file": "/stickers/stars/star-01.svg",
    "keywords": [
      "stars",
      "stars",
      "ดวงดาว",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "stars-02",
    "category": "stars",
    "name": "sparkle-02",
    "file": "/stickers/stars/sparkle-02.svg",
    "keywords": [
      "stars",
      "stars",
      "ดวงดาว",
      "sparkle",
      "shine",
      "ประกาย"
    ]
  },
  {
    "id": "stars-03",
    "category": "stars",
    "name": "star-03",
    "file": "/stickers/stars/star-03.svg",
    "keywords": [
      "stars",
      "stars",
      "ดวงดาว",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "stars-04",
    "category": "stars",
    "name": "sparkle-04",
    "file": "/stickers/stars/sparkle-04.svg",
    "keywords": [
      "stars",
      "stars",
      "ดวงดาว",
      "sparkle",
      "shine",
      "ประกาย"
    ]
  },
  {
    "id": "stars-05",
    "category": "stars",
    "name": "star-05",
    "file": "/stickers/stars/star-05.svg",
    "keywords": [
      "stars",
      "stars",
      "ดวงดาว",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "stars-06",
    "category": "stars",
    "name": "sparkle-06",
    "file": "/stickers/stars/sparkle-06.svg",
    "keywords": [
      "stars",
      "stars",
      "ดวงดาว",
      "sparkle",
      "shine",
      "ประกาย"
    ]
  },
  {
    "id": "stars-07",
    "category": "stars",
    "name": "star-07",
    "file": "/stickers/stars/star-07.svg",
    "keywords": [
      "stars",
      "stars",
      "ดวงดาว",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "stars-08",
    "category": "stars",
    "name": "sparkle-08",
    "file": "/stickers/stars/sparkle-08.svg",
    "keywords": [
      "stars",
      "stars",
      "ดวงดาว",
      "sparkle",
      "shine",
      "ประกาย"
    ]
  },
  {
    "id": "stars-09",
    "category": "stars",
    "name": "star-09",
    "file": "/stickers/stars/star-09.svg",
    "keywords": [
      "stars",
      "stars",
      "ดวงดาว",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "stars-10",
    "category": "stars",
    "name": "sparkle-10",
    "file": "/stickers/stars/sparkle-10.svg",
    "keywords": [
      "stars",
      "stars",
      "ดวงดาว",
      "sparkle",
      "shine",
      "ประกาย"
    ]
  },
  {
    "id": "stars-11",
    "category": "stars",
    "name": "star-11",
    "file": "/stickers/stars/star-11.svg",
    "keywords": [
      "stars",
      "stars",
      "ดวงดาว",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "stars-12",
    "category": "stars",
    "name": "sparkle-12",
    "file": "/stickers/stars/sparkle-12.svg",
    "keywords": [
      "stars",
      "stars",
      "ดวงดาว",
      "sparkle",
      "shine",
      "ประกาย"
    ]
  },
  {
    "id": "clouds-01",
    "category": "clouds",
    "name": "cloud-01",
    "file": "/stickers/clouds/cloud-01.svg",
    "keywords": [
      "clouds",
      "clouds",
      "เมฆ",
      "cloud",
      "เมฆ"
    ]
  },
  {
    "id": "clouds-02",
    "category": "clouds",
    "name": "cloud-02",
    "file": "/stickers/clouds/cloud-02.svg",
    "keywords": [
      "clouds",
      "clouds",
      "เมฆ",
      "cloud",
      "เมฆ"
    ]
  },
  {
    "id": "clouds-03",
    "category": "clouds",
    "name": "cloud-03",
    "file": "/stickers/clouds/cloud-03.svg",
    "keywords": [
      "clouds",
      "clouds",
      "เมฆ",
      "cloud",
      "เมฆ"
    ]
  },
  {
    "id": "clouds-04",
    "category": "clouds",
    "name": "cloud-04",
    "file": "/stickers/clouds/cloud-04.svg",
    "keywords": [
      "clouds",
      "clouds",
      "เมฆ",
      "cloud",
      "เมฆ"
    ]
  },
  {
    "id": "clouds-05",
    "category": "clouds",
    "name": "cloud-05",
    "file": "/stickers/clouds/cloud-05.svg",
    "keywords": [
      "clouds",
      "clouds",
      "เมฆ",
      "cloud",
      "เมฆ"
    ]
  },
  {
    "id": "clouds-06",
    "category": "clouds",
    "name": "cloud-06",
    "file": "/stickers/clouds/cloud-06.svg",
    "keywords": [
      "clouds",
      "clouds",
      "เมฆ",
      "cloud",
      "เมฆ"
    ]
  },
  {
    "id": "clouds-07",
    "category": "clouds",
    "name": "cloud-07",
    "file": "/stickers/clouds/cloud-07.svg",
    "keywords": [
      "clouds",
      "clouds",
      "เมฆ",
      "cloud",
      "เมฆ"
    ]
  },
  {
    "id": "clouds-08",
    "category": "clouds",
    "name": "cloud-08",
    "file": "/stickers/clouds/cloud-08.svg",
    "keywords": [
      "clouds",
      "clouds",
      "เมฆ",
      "cloud",
      "เมฆ"
    ]
  },
  {
    "id": "clouds-09",
    "category": "clouds",
    "name": "cloud-09",
    "file": "/stickers/clouds/cloud-09.svg",
    "keywords": [
      "clouds",
      "clouds",
      "เมฆ",
      "cloud",
      "เมฆ"
    ]
  },
  {
    "id": "clouds-10",
    "category": "clouds",
    "name": "cloud-10",
    "file": "/stickers/clouds/cloud-10.svg",
    "keywords": [
      "clouds",
      "clouds",
      "เมฆ",
      "cloud",
      "เมฆ"
    ]
  },
  {
    "id": "clouds-11",
    "category": "clouds",
    "name": "cloud-11",
    "file": "/stickers/clouds/cloud-11.svg",
    "keywords": [
      "clouds",
      "clouds",
      "เมฆ",
      "cloud",
      "เมฆ"
    ]
  },
  {
    "id": "clouds-12",
    "category": "clouds",
    "name": "cloud-12",
    "file": "/stickers/clouds/cloud-12.svg",
    "keywords": [
      "clouds",
      "clouds",
      "เมฆ",
      "cloud",
      "เมฆ"
    ]
  },
  {
    "id": "birthday-01",
    "category": "birthday",
    "name": "cake-01",
    "file": "/stickers/birthday/cake-01.svg",
    "keywords": [
      "birthday",
      "birthday",
      "วันเกิด",
      "cake",
      "เค้ก"
    ]
  },
  {
    "id": "birthday-02",
    "category": "birthday",
    "name": "balloon-02",
    "file": "/stickers/birthday/balloon-02.svg",
    "keywords": [
      "birthday",
      "birthday",
      "วันเกิด",
      "balloon",
      "ลูกโป่ง"
    ]
  },
  {
    "id": "birthday-03",
    "category": "birthday",
    "name": "gift-03",
    "file": "/stickers/birthday/gift-03.svg",
    "keywords": [
      "birthday",
      "birthday",
      "วันเกิด",
      "gift",
      "present",
      "ของขวัญ"
    ]
  },
  {
    "id": "birthday-04",
    "category": "birthday",
    "name": "cake-04",
    "file": "/stickers/birthday/cake-04.svg",
    "keywords": [
      "birthday",
      "birthday",
      "วันเกิด",
      "cake",
      "เค้ก"
    ]
  },
  {
    "id": "birthday-05",
    "category": "birthday",
    "name": "balloon-05",
    "file": "/stickers/birthday/balloon-05.svg",
    "keywords": [
      "birthday",
      "birthday",
      "วันเกิด",
      "balloon",
      "ลูกโป่ง"
    ]
  },
  {
    "id": "birthday-06",
    "category": "birthday",
    "name": "gift-06",
    "file": "/stickers/birthday/gift-06.svg",
    "keywords": [
      "birthday",
      "birthday",
      "วันเกิด",
      "gift",
      "present",
      "ของขวัญ"
    ]
  },
  {
    "id": "birthday-07",
    "category": "birthday",
    "name": "cake-07",
    "file": "/stickers/birthday/cake-07.svg",
    "keywords": [
      "birthday",
      "birthday",
      "วันเกิด",
      "cake",
      "เค้ก"
    ]
  },
  {
    "id": "birthday-08",
    "category": "birthday",
    "name": "balloon-08",
    "file": "/stickers/birthday/balloon-08.svg",
    "keywords": [
      "birthday",
      "birthday",
      "วันเกิด",
      "balloon",
      "ลูกโป่ง"
    ]
  },
  {
    "id": "birthday-09",
    "category": "birthday",
    "name": "gift-09",
    "file": "/stickers/birthday/gift-09.svg",
    "keywords": [
      "birthday",
      "birthday",
      "วันเกิด",
      "gift",
      "present",
      "ของขวัญ"
    ]
  },
  {
    "id": "birthday-10",
    "category": "birthday",
    "name": "cake-10",
    "file": "/stickers/birthday/cake-10.svg",
    "keywords": [
      "birthday",
      "birthday",
      "วันเกิด",
      "cake",
      "เค้ก"
    ]
  },
  {
    "id": "birthday-11",
    "category": "birthday",
    "name": "balloon-11",
    "file": "/stickers/birthday/balloon-11.svg",
    "keywords": [
      "birthday",
      "birthday",
      "วันเกิด",
      "balloon",
      "ลูกโป่ง"
    ]
  },
  {
    "id": "birthday-12",
    "category": "birthday",
    "name": "gift-12",
    "file": "/stickers/birthday/gift-12.svg",
    "keywords": [
      "birthday",
      "birthday",
      "วันเกิด",
      "gift",
      "present",
      "ของขวัญ"
    ]
  },
  {
    "id": "baby-01",
    "category": "baby",
    "name": "heart-01",
    "file": "/stickers/baby/heart-01.svg",
    "keywords": [
      "baby",
      "baby",
      "เด็กน้อย",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "baby-02",
    "category": "baby",
    "name": "star-02",
    "file": "/stickers/baby/star-02.svg",
    "keywords": [
      "baby",
      "baby",
      "เด็กน้อย",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "baby-03",
    "category": "baby",
    "name": "moon-03",
    "file": "/stickers/baby/moon-03.svg",
    "keywords": [
      "baby",
      "baby",
      "เด็กน้อย",
      "moon",
      "พระจันทร์"
    ]
  },
  {
    "id": "baby-04",
    "category": "baby",
    "name": "cloud-04",
    "file": "/stickers/baby/cloud-04.svg",
    "keywords": [
      "baby",
      "baby",
      "เด็กน้อย",
      "cloud",
      "เมฆ"
    ]
  },
  {
    "id": "baby-05",
    "category": "baby",
    "name": "heart-05",
    "file": "/stickers/baby/heart-05.svg",
    "keywords": [
      "baby",
      "baby",
      "เด็กน้อย",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "baby-06",
    "category": "baby",
    "name": "star-06",
    "file": "/stickers/baby/star-06.svg",
    "keywords": [
      "baby",
      "baby",
      "เด็กน้อย",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "baby-07",
    "category": "baby",
    "name": "moon-07",
    "file": "/stickers/baby/moon-07.svg",
    "keywords": [
      "baby",
      "baby",
      "เด็กน้อย",
      "moon",
      "พระจันทร์"
    ]
  },
  {
    "id": "baby-08",
    "category": "baby",
    "name": "cloud-08",
    "file": "/stickers/baby/cloud-08.svg",
    "keywords": [
      "baby",
      "baby",
      "เด็กน้อย",
      "cloud",
      "เมฆ"
    ]
  },
  {
    "id": "baby-09",
    "category": "baby",
    "name": "heart-09",
    "file": "/stickers/baby/heart-09.svg",
    "keywords": [
      "baby",
      "baby",
      "เด็กน้อย",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "baby-10",
    "category": "baby",
    "name": "star-10",
    "file": "/stickers/baby/star-10.svg",
    "keywords": [
      "baby",
      "baby",
      "เด็กน้อย",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "baby-11",
    "category": "baby",
    "name": "moon-11",
    "file": "/stickers/baby/moon-11.svg",
    "keywords": [
      "baby",
      "baby",
      "เด็กน้อย",
      "moon",
      "พระจันทร์"
    ]
  },
  {
    "id": "baby-12",
    "category": "baby",
    "name": "cloud-12",
    "file": "/stickers/baby/cloud-12.svg",
    "keywords": [
      "baby",
      "baby",
      "เด็กน้อย",
      "cloud",
      "เมฆ"
    ]
  },
  {
    "id": "pets-01",
    "category": "pets",
    "name": "paw-01",
    "file": "/stickers/pets/paw-01.svg",
    "keywords": [
      "pets",
      "pets",
      "สัตว์เลี้ยง",
      "paw",
      "อุ้งเท้า",
      "dog",
      "cat"
    ]
  },
  {
    "id": "pets-02",
    "category": "pets",
    "name": "fish-02",
    "file": "/stickers/pets/fish-02.svg",
    "keywords": [
      "pets",
      "pets",
      "สัตว์เลี้ยง",
      "fish",
      "ปลา"
    ]
  },
  {
    "id": "pets-03",
    "category": "pets",
    "name": "paw-03",
    "file": "/stickers/pets/paw-03.svg",
    "keywords": [
      "pets",
      "pets",
      "สัตว์เลี้ยง",
      "paw",
      "อุ้งเท้า",
      "dog",
      "cat"
    ]
  },
  {
    "id": "pets-04",
    "category": "pets",
    "name": "fish-04",
    "file": "/stickers/pets/fish-04.svg",
    "keywords": [
      "pets",
      "pets",
      "สัตว์เลี้ยง",
      "fish",
      "ปลา"
    ]
  },
  {
    "id": "pets-05",
    "category": "pets",
    "name": "paw-05",
    "file": "/stickers/pets/paw-05.svg",
    "keywords": [
      "pets",
      "pets",
      "สัตว์เลี้ยง",
      "paw",
      "อุ้งเท้า",
      "dog",
      "cat"
    ]
  },
  {
    "id": "pets-06",
    "category": "pets",
    "name": "fish-06",
    "file": "/stickers/pets/fish-06.svg",
    "keywords": [
      "pets",
      "pets",
      "สัตว์เลี้ยง",
      "fish",
      "ปลา"
    ]
  },
  {
    "id": "pets-07",
    "category": "pets",
    "name": "paw-07",
    "file": "/stickers/pets/paw-07.svg",
    "keywords": [
      "pets",
      "pets",
      "สัตว์เลี้ยง",
      "paw",
      "อุ้งเท้า",
      "dog",
      "cat"
    ]
  },
  {
    "id": "pets-08",
    "category": "pets",
    "name": "fish-08",
    "file": "/stickers/pets/fish-08.svg",
    "keywords": [
      "pets",
      "pets",
      "สัตว์เลี้ยง",
      "fish",
      "ปลา"
    ]
  },
  {
    "id": "pets-09",
    "category": "pets",
    "name": "paw-09",
    "file": "/stickers/pets/paw-09.svg",
    "keywords": [
      "pets",
      "pets",
      "สัตว์เลี้ยง",
      "paw",
      "อุ้งเท้า",
      "dog",
      "cat"
    ]
  },
  {
    "id": "pets-10",
    "category": "pets",
    "name": "fish-10",
    "file": "/stickers/pets/fish-10.svg",
    "keywords": [
      "pets",
      "pets",
      "สัตว์เลี้ยง",
      "fish",
      "ปลา"
    ]
  },
  {
    "id": "pets-11",
    "category": "pets",
    "name": "paw-11",
    "file": "/stickers/pets/paw-11.svg",
    "keywords": [
      "pets",
      "pets",
      "สัตว์เลี้ยง",
      "paw",
      "อุ้งเท้า",
      "dog",
      "cat"
    ]
  },
  {
    "id": "pets-12",
    "category": "pets",
    "name": "fish-12",
    "file": "/stickers/pets/fish-12.svg",
    "keywords": [
      "pets",
      "pets",
      "สัตว์เลี้ยง",
      "fish",
      "ปลา"
    ]
  },
  {
    "id": "christmas-01",
    "category": "christmas",
    "name": "tree-01",
    "file": "/stickers/christmas/tree-01.svg",
    "keywords": [
      "christmas",
      "christmas",
      "คริสต์มาส",
      "tree",
      "ต้นไม้",
      "pine"
    ]
  },
  {
    "id": "christmas-02",
    "category": "christmas",
    "name": "gift-02",
    "file": "/stickers/christmas/gift-02.svg",
    "keywords": [
      "christmas",
      "christmas",
      "คริสต์มาส",
      "gift",
      "present",
      "ของขวัญ"
    ]
  },
  {
    "id": "christmas-03",
    "category": "christmas",
    "name": "star-03",
    "file": "/stickers/christmas/star-03.svg",
    "keywords": [
      "christmas",
      "christmas",
      "คริสต์มาส",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "christmas-04",
    "category": "christmas",
    "name": "tree-04",
    "file": "/stickers/christmas/tree-04.svg",
    "keywords": [
      "christmas",
      "christmas",
      "คริสต์มาส",
      "tree",
      "ต้นไม้",
      "pine"
    ]
  },
  {
    "id": "christmas-05",
    "category": "christmas",
    "name": "gift-05",
    "file": "/stickers/christmas/gift-05.svg",
    "keywords": [
      "christmas",
      "christmas",
      "คริสต์มาส",
      "gift",
      "present",
      "ของขวัญ"
    ]
  },
  {
    "id": "christmas-06",
    "category": "christmas",
    "name": "star-06",
    "file": "/stickers/christmas/star-06.svg",
    "keywords": [
      "christmas",
      "christmas",
      "คริสต์มาส",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "christmas-07",
    "category": "christmas",
    "name": "tree-07",
    "file": "/stickers/christmas/tree-07.svg",
    "keywords": [
      "christmas",
      "christmas",
      "คริสต์มาส",
      "tree",
      "ต้นไม้",
      "pine"
    ]
  },
  {
    "id": "christmas-08",
    "category": "christmas",
    "name": "gift-08",
    "file": "/stickers/christmas/gift-08.svg",
    "keywords": [
      "christmas",
      "christmas",
      "คริสต์มาส",
      "gift",
      "present",
      "ของขวัญ"
    ]
  },
  {
    "id": "christmas-09",
    "category": "christmas",
    "name": "star-09",
    "file": "/stickers/christmas/star-09.svg",
    "keywords": [
      "christmas",
      "christmas",
      "คริสต์มาส",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "christmas-10",
    "category": "christmas",
    "name": "tree-10",
    "file": "/stickers/christmas/tree-10.svg",
    "keywords": [
      "christmas",
      "christmas",
      "คริสต์มาส",
      "tree",
      "ต้นไม้",
      "pine"
    ]
  },
  {
    "id": "christmas-11",
    "category": "christmas",
    "name": "gift-11",
    "file": "/stickers/christmas/gift-11.svg",
    "keywords": [
      "christmas",
      "christmas",
      "คริสต์มาส",
      "gift",
      "present",
      "ของขวัญ"
    ]
  },
  {
    "id": "christmas-12",
    "category": "christmas",
    "name": "star-12",
    "file": "/stickers/christmas/star-12.svg",
    "keywords": [
      "christmas",
      "christmas",
      "คริสต์มาส",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "celebration-01",
    "category": "celebration",
    "name": "balloon-01",
    "file": "/stickers/celebration/balloon-01.svg",
    "keywords": [
      "celebration",
      "celebration",
      "เฉลิมฉลอง",
      "balloon",
      "ลูกโป่ง"
    ]
  },
  {
    "id": "celebration-02",
    "category": "celebration",
    "name": "sparkle-02",
    "file": "/stickers/celebration/sparkle-02.svg",
    "keywords": [
      "celebration",
      "celebration",
      "เฉลิมฉลอง",
      "sparkle",
      "shine",
      "ประกาย"
    ]
  },
  {
    "id": "celebration-03",
    "category": "celebration",
    "name": "gift-03",
    "file": "/stickers/celebration/gift-03.svg",
    "keywords": [
      "celebration",
      "celebration",
      "เฉลิมฉลอง",
      "gift",
      "present",
      "ของขวัญ"
    ]
  },
  {
    "id": "celebration-04",
    "category": "celebration",
    "name": "balloon-04",
    "file": "/stickers/celebration/balloon-04.svg",
    "keywords": [
      "celebration",
      "celebration",
      "เฉลิมฉลอง",
      "balloon",
      "ลูกโป่ง"
    ]
  },
  {
    "id": "celebration-05",
    "category": "celebration",
    "name": "sparkle-05",
    "file": "/stickers/celebration/sparkle-05.svg",
    "keywords": [
      "celebration",
      "celebration",
      "เฉลิมฉลอง",
      "sparkle",
      "shine",
      "ประกาย"
    ]
  },
  {
    "id": "celebration-06",
    "category": "celebration",
    "name": "gift-06",
    "file": "/stickers/celebration/gift-06.svg",
    "keywords": [
      "celebration",
      "celebration",
      "เฉลิมฉลอง",
      "gift",
      "present",
      "ของขวัญ"
    ]
  },
  {
    "id": "celebration-07",
    "category": "celebration",
    "name": "balloon-07",
    "file": "/stickers/celebration/balloon-07.svg",
    "keywords": [
      "celebration",
      "celebration",
      "เฉลิมฉลอง",
      "balloon",
      "ลูกโป่ง"
    ]
  },
  {
    "id": "celebration-08",
    "category": "celebration",
    "name": "sparkle-08",
    "file": "/stickers/celebration/sparkle-08.svg",
    "keywords": [
      "celebration",
      "celebration",
      "เฉลิมฉลอง",
      "sparkle",
      "shine",
      "ประกาย"
    ]
  },
  {
    "id": "celebration-09",
    "category": "celebration",
    "name": "gift-09",
    "file": "/stickers/celebration/gift-09.svg",
    "keywords": [
      "celebration",
      "celebration",
      "เฉลิมฉลอง",
      "gift",
      "present",
      "ของขวัญ"
    ]
  },
  {
    "id": "celebration-10",
    "category": "celebration",
    "name": "balloon-10",
    "file": "/stickers/celebration/balloon-10.svg",
    "keywords": [
      "celebration",
      "celebration",
      "เฉลิมฉลอง",
      "balloon",
      "ลูกโป่ง"
    ]
  },
  {
    "id": "celebration-11",
    "category": "celebration",
    "name": "sparkle-11",
    "file": "/stickers/celebration/sparkle-11.svg",
    "keywords": [
      "celebration",
      "celebration",
      "เฉลิมฉลอง",
      "sparkle",
      "shine",
      "ประกาย"
    ]
  },
  {
    "id": "celebration-12",
    "category": "celebration",
    "name": "gift-12",
    "file": "/stickers/celebration/gift-12.svg",
    "keywords": [
      "celebration",
      "celebration",
      "เฉลิมฉลอง",
      "gift",
      "present",
      "ของขวัญ"
    ]
  },
  {
    "id": "travel-01",
    "category": "travel",
    "name": "airplane-01",
    "file": "/stickers/travel/airplane-01.svg",
    "keywords": [
      "travel",
      "travel",
      "ท่องเที่ยว",
      "airplane",
      "plane",
      "เครื่องบิน"
    ]
  },
  {
    "id": "travel-02",
    "category": "travel",
    "name": "sun-02",
    "file": "/stickers/travel/sun-02.svg",
    "keywords": [
      "travel",
      "travel",
      "ท่องเที่ยว",
      "sun",
      "พระอาทิตย์"
    ]
  },
  {
    "id": "travel-03",
    "category": "travel",
    "name": "airplane-03",
    "file": "/stickers/travel/airplane-03.svg",
    "keywords": [
      "travel",
      "travel",
      "ท่องเที่ยว",
      "airplane",
      "plane",
      "เครื่องบิน"
    ]
  },
  {
    "id": "travel-04",
    "category": "travel",
    "name": "sun-04",
    "file": "/stickers/travel/sun-04.svg",
    "keywords": [
      "travel",
      "travel",
      "ท่องเที่ยว",
      "sun",
      "พระอาทิตย์"
    ]
  },
  {
    "id": "travel-05",
    "category": "travel",
    "name": "airplane-05",
    "file": "/stickers/travel/airplane-05.svg",
    "keywords": [
      "travel",
      "travel",
      "ท่องเที่ยว",
      "airplane",
      "plane",
      "เครื่องบิน"
    ]
  },
  {
    "id": "travel-06",
    "category": "travel",
    "name": "sun-06",
    "file": "/stickers/travel/sun-06.svg",
    "keywords": [
      "travel",
      "travel",
      "ท่องเที่ยว",
      "sun",
      "พระอาทิตย์"
    ]
  },
  {
    "id": "travel-07",
    "category": "travel",
    "name": "airplane-07",
    "file": "/stickers/travel/airplane-07.svg",
    "keywords": [
      "travel",
      "travel",
      "ท่องเที่ยว",
      "airplane",
      "plane",
      "เครื่องบิน"
    ]
  },
  {
    "id": "travel-08",
    "category": "travel",
    "name": "sun-08",
    "file": "/stickers/travel/sun-08.svg",
    "keywords": [
      "travel",
      "travel",
      "ท่องเที่ยว",
      "sun",
      "พระอาทิตย์"
    ]
  },
  {
    "id": "travel-09",
    "category": "travel",
    "name": "airplane-09",
    "file": "/stickers/travel/airplane-09.svg",
    "keywords": [
      "travel",
      "travel",
      "ท่องเที่ยว",
      "airplane",
      "plane",
      "เครื่องบิน"
    ]
  },
  {
    "id": "travel-10",
    "category": "travel",
    "name": "sun-10",
    "file": "/stickers/travel/sun-10.svg",
    "keywords": [
      "travel",
      "travel",
      "ท่องเที่ยว",
      "sun",
      "พระอาทิตย์"
    ]
  },
  {
    "id": "travel-11",
    "category": "travel",
    "name": "airplane-11",
    "file": "/stickers/travel/airplane-11.svg",
    "keywords": [
      "travel",
      "travel",
      "ท่องเที่ยว",
      "airplane",
      "plane",
      "เครื่องบิน"
    ]
  },
  {
    "id": "travel-12",
    "category": "travel",
    "name": "sun-12",
    "file": "/stickers/travel/sun-12.svg",
    "keywords": [
      "travel",
      "travel",
      "ท่องเที่ยว",
      "sun",
      "พระอาทิตย์"
    ]
  },
  {
    "id": "summer-01",
    "category": "summer",
    "name": "sun-01",
    "file": "/stickers/summer/sun-01.svg",
    "keywords": [
      "summer",
      "summer",
      "ฤดูร้อน",
      "sun",
      "พระอาทิตย์"
    ]
  },
  {
    "id": "summer-02",
    "category": "summer",
    "name": "icecream-02",
    "file": "/stickers/summer/icecream-02.svg",
    "keywords": [
      "summer",
      "summer",
      "ฤดูร้อน",
      "ice cream",
      "ไอติม",
      "ไอศกรีม"
    ]
  },
  {
    "id": "summer-03",
    "category": "summer",
    "name": "fish-03",
    "file": "/stickers/summer/fish-03.svg",
    "keywords": [
      "summer",
      "summer",
      "ฤดูร้อน",
      "fish",
      "ปลา"
    ]
  },
  {
    "id": "summer-04",
    "category": "summer",
    "name": "sun-04",
    "file": "/stickers/summer/sun-04.svg",
    "keywords": [
      "summer",
      "summer",
      "ฤดูร้อน",
      "sun",
      "พระอาทิตย์"
    ]
  },
  {
    "id": "summer-05",
    "category": "summer",
    "name": "icecream-05",
    "file": "/stickers/summer/icecream-05.svg",
    "keywords": [
      "summer",
      "summer",
      "ฤดูร้อน",
      "ice cream",
      "ไอติม",
      "ไอศกรีม"
    ]
  },
  {
    "id": "summer-06",
    "category": "summer",
    "name": "fish-06",
    "file": "/stickers/summer/fish-06.svg",
    "keywords": [
      "summer",
      "summer",
      "ฤดูร้อน",
      "fish",
      "ปลา"
    ]
  },
  {
    "id": "summer-07",
    "category": "summer",
    "name": "sun-07",
    "file": "/stickers/summer/sun-07.svg",
    "keywords": [
      "summer",
      "summer",
      "ฤดูร้อน",
      "sun",
      "พระอาทิตย์"
    ]
  },
  {
    "id": "summer-08",
    "category": "summer",
    "name": "icecream-08",
    "file": "/stickers/summer/icecream-08.svg",
    "keywords": [
      "summer",
      "summer",
      "ฤดูร้อน",
      "ice cream",
      "ไอติม",
      "ไอศกรีม"
    ]
  },
  {
    "id": "summer-09",
    "category": "summer",
    "name": "fish-09",
    "file": "/stickers/summer/fish-09.svg",
    "keywords": [
      "summer",
      "summer",
      "ฤดูร้อน",
      "fish",
      "ปลา"
    ]
  },
  {
    "id": "summer-10",
    "category": "summer",
    "name": "sun-10",
    "file": "/stickers/summer/sun-10.svg",
    "keywords": [
      "summer",
      "summer",
      "ฤดูร้อน",
      "sun",
      "พระอาทิตย์"
    ]
  },
  {
    "id": "summer-11",
    "category": "summer",
    "name": "icecream-11",
    "file": "/stickers/summer/icecream-11.svg",
    "keywords": [
      "summer",
      "summer",
      "ฤดูร้อน",
      "ice cream",
      "ไอติม",
      "ไอศกรีม"
    ]
  },
  {
    "id": "summer-12",
    "category": "summer",
    "name": "fish-12",
    "file": "/stickers/summer/fish-12.svg",
    "keywords": [
      "summer",
      "summer",
      "ฤดูร้อน",
      "fish",
      "ปลา"
    ]
  },
  {
    "id": "school-01",
    "category": "school",
    "name": "pencil-01",
    "file": "/stickers/school/pencil-01.svg",
    "keywords": [
      "school",
      "school",
      "โรงเรียน",
      "pencil",
      "ดินสอ"
    ]
  },
  {
    "id": "school-02",
    "category": "school",
    "name": "book-02",
    "file": "/stickers/school/book-02.svg",
    "keywords": [
      "school",
      "school",
      "โรงเรียน",
      "book",
      "หนังสือ"
    ]
  },
  {
    "id": "school-03",
    "category": "school",
    "name": "star-03",
    "file": "/stickers/school/star-03.svg",
    "keywords": [
      "school",
      "school",
      "โรงเรียน",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "school-04",
    "category": "school",
    "name": "pencil-04",
    "file": "/stickers/school/pencil-04.svg",
    "keywords": [
      "school",
      "school",
      "โรงเรียน",
      "pencil",
      "ดินสอ"
    ]
  },
  {
    "id": "school-05",
    "category": "school",
    "name": "book-05",
    "file": "/stickers/school/book-05.svg",
    "keywords": [
      "school",
      "school",
      "โรงเรียน",
      "book",
      "หนังสือ"
    ]
  },
  {
    "id": "school-06",
    "category": "school",
    "name": "star-06",
    "file": "/stickers/school/star-06.svg",
    "keywords": [
      "school",
      "school",
      "โรงเรียน",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "school-07",
    "category": "school",
    "name": "pencil-07",
    "file": "/stickers/school/pencil-07.svg",
    "keywords": [
      "school",
      "school",
      "โรงเรียน",
      "pencil",
      "ดินสอ"
    ]
  },
  {
    "id": "school-08",
    "category": "school",
    "name": "book-08",
    "file": "/stickers/school/book-08.svg",
    "keywords": [
      "school",
      "school",
      "โรงเรียน",
      "book",
      "หนังสือ"
    ]
  },
  {
    "id": "school-09",
    "category": "school",
    "name": "star-09",
    "file": "/stickers/school/star-09.svg",
    "keywords": [
      "school",
      "school",
      "โรงเรียน",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "school-10",
    "category": "school",
    "name": "pencil-10",
    "file": "/stickers/school/pencil-10.svg",
    "keywords": [
      "school",
      "school",
      "โรงเรียน",
      "pencil",
      "ดินสอ"
    ]
  },
  {
    "id": "school-11",
    "category": "school",
    "name": "book-11",
    "file": "/stickers/school/book-11.svg",
    "keywords": [
      "school",
      "school",
      "โรงเรียน",
      "book",
      "หนังสือ"
    ]
  },
  {
    "id": "school-12",
    "category": "school",
    "name": "star-12",
    "file": "/stickers/school/star-12.svg",
    "keywords": [
      "school",
      "school",
      "โรงเรียน",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "wedding-01",
    "category": "wedding",
    "name": "gem-01",
    "file": "/stickers/wedding/gem-01.svg",
    "keywords": [
      "wedding",
      "wedding",
      "งานแต่ง",
      "gem",
      "diamond",
      "เพชร"
    ]
  },
  {
    "id": "wedding-02",
    "category": "wedding",
    "name": "bow-02",
    "file": "/stickers/wedding/bow-02.svg",
    "keywords": [
      "wedding",
      "wedding",
      "งานแต่ง",
      "bow",
      "ribbon",
      "โบว์"
    ]
  },
  {
    "id": "wedding-03",
    "category": "wedding",
    "name": "heart-03",
    "file": "/stickers/wedding/heart-03.svg",
    "keywords": [
      "wedding",
      "wedding",
      "งานแต่ง",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "wedding-04",
    "category": "wedding",
    "name": "gem-04",
    "file": "/stickers/wedding/gem-04.svg",
    "keywords": [
      "wedding",
      "wedding",
      "งานแต่ง",
      "gem",
      "diamond",
      "เพชร"
    ]
  },
  {
    "id": "wedding-05",
    "category": "wedding",
    "name": "bow-05",
    "file": "/stickers/wedding/bow-05.svg",
    "keywords": [
      "wedding",
      "wedding",
      "งานแต่ง",
      "bow",
      "ribbon",
      "โบว์"
    ]
  },
  {
    "id": "wedding-06",
    "category": "wedding",
    "name": "heart-06",
    "file": "/stickers/wedding/heart-06.svg",
    "keywords": [
      "wedding",
      "wedding",
      "งานแต่ง",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "wedding-07",
    "category": "wedding",
    "name": "gem-07",
    "file": "/stickers/wedding/gem-07.svg",
    "keywords": [
      "wedding",
      "wedding",
      "งานแต่ง",
      "gem",
      "diamond",
      "เพชร"
    ]
  },
  {
    "id": "wedding-08",
    "category": "wedding",
    "name": "bow-08",
    "file": "/stickers/wedding/bow-08.svg",
    "keywords": [
      "wedding",
      "wedding",
      "งานแต่ง",
      "bow",
      "ribbon",
      "โบว์"
    ]
  },
  {
    "id": "wedding-09",
    "category": "wedding",
    "name": "heart-09",
    "file": "/stickers/wedding/heart-09.svg",
    "keywords": [
      "wedding",
      "wedding",
      "งานแต่ง",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "wedding-10",
    "category": "wedding",
    "name": "gem-10",
    "file": "/stickers/wedding/gem-10.svg",
    "keywords": [
      "wedding",
      "wedding",
      "งานแต่ง",
      "gem",
      "diamond",
      "เพชร"
    ]
  },
  {
    "id": "wedding-11",
    "category": "wedding",
    "name": "bow-11",
    "file": "/stickers/wedding/bow-11.svg",
    "keywords": [
      "wedding",
      "wedding",
      "งานแต่ง",
      "bow",
      "ribbon",
      "โบว์"
    ]
  },
  {
    "id": "wedding-12",
    "category": "wedding",
    "name": "heart-12",
    "file": "/stickers/wedding/heart-12.svg",
    "keywords": [
      "wedding",
      "wedding",
      "งานแต่ง",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "cartoon-01",
    "category": "cartoon",
    "name": "smiley-01",
    "file": "/stickers/cartoon/smiley-01.svg",
    "keywords": [
      "cartoon",
      "cartoon",
      "การ์ตูน",
      "smiley",
      "face",
      "หน้ายิ้ม"
    ]
  },
  {
    "id": "cartoon-02",
    "category": "cartoon",
    "name": "star-02",
    "file": "/stickers/cartoon/star-02.svg",
    "keywords": [
      "cartoon",
      "cartoon",
      "การ์ตูน",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "cartoon-03",
    "category": "cartoon",
    "name": "smiley-03",
    "file": "/stickers/cartoon/smiley-03.svg",
    "keywords": [
      "cartoon",
      "cartoon",
      "การ์ตูน",
      "smiley",
      "face",
      "หน้ายิ้ม"
    ]
  },
  {
    "id": "cartoon-04",
    "category": "cartoon",
    "name": "star-04",
    "file": "/stickers/cartoon/star-04.svg",
    "keywords": [
      "cartoon",
      "cartoon",
      "การ์ตูน",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "cartoon-05",
    "category": "cartoon",
    "name": "smiley-05",
    "file": "/stickers/cartoon/smiley-05.svg",
    "keywords": [
      "cartoon",
      "cartoon",
      "การ์ตูน",
      "smiley",
      "face",
      "หน้ายิ้ม"
    ]
  },
  {
    "id": "cartoon-06",
    "category": "cartoon",
    "name": "star-06",
    "file": "/stickers/cartoon/star-06.svg",
    "keywords": [
      "cartoon",
      "cartoon",
      "การ์ตูน",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "cartoon-07",
    "category": "cartoon",
    "name": "smiley-07",
    "file": "/stickers/cartoon/smiley-07.svg",
    "keywords": [
      "cartoon",
      "cartoon",
      "การ์ตูน",
      "smiley",
      "face",
      "หน้ายิ้ม"
    ]
  },
  {
    "id": "cartoon-08",
    "category": "cartoon",
    "name": "star-08",
    "file": "/stickers/cartoon/star-08.svg",
    "keywords": [
      "cartoon",
      "cartoon",
      "การ์ตูน",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "cartoon-09",
    "category": "cartoon",
    "name": "smiley-09",
    "file": "/stickers/cartoon/smiley-09.svg",
    "keywords": [
      "cartoon",
      "cartoon",
      "การ์ตูน",
      "smiley",
      "face",
      "หน้ายิ้ม"
    ]
  },
  {
    "id": "cartoon-10",
    "category": "cartoon",
    "name": "star-10",
    "file": "/stickers/cartoon/star-10.svg",
    "keywords": [
      "cartoon",
      "cartoon",
      "การ์ตูน",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "cartoon-11",
    "category": "cartoon",
    "name": "smiley-11",
    "file": "/stickers/cartoon/smiley-11.svg",
    "keywords": [
      "cartoon",
      "cartoon",
      "การ์ตูน",
      "smiley",
      "face",
      "หน้ายิ้ม"
    ]
  },
  {
    "id": "cartoon-12",
    "category": "cartoon",
    "name": "star-12",
    "file": "/stickers/cartoon/star-12.svg",
    "keywords": [
      "cartoon",
      "cartoon",
      "การ์ตูน",
      "star",
      "ดาว"
    ]
  },
  {
    "id": "food-01",
    "category": "food",
    "name": "icecream-01",
    "file": "/stickers/food/icecream-01.svg",
    "keywords": [
      "food",
      "food",
      "อาหาร",
      "ice cream",
      "ไอติม",
      "ไอศกรีม"
    ]
  },
  {
    "id": "food-02",
    "category": "food",
    "name": "cake-02",
    "file": "/stickers/food/cake-02.svg",
    "keywords": [
      "food",
      "food",
      "อาหาร",
      "cake",
      "เค้ก"
    ]
  },
  {
    "id": "food-03",
    "category": "food",
    "name": "icecream-03",
    "file": "/stickers/food/icecream-03.svg",
    "keywords": [
      "food",
      "food",
      "อาหาร",
      "ice cream",
      "ไอติม",
      "ไอศกรีม"
    ]
  },
  {
    "id": "food-04",
    "category": "food",
    "name": "cake-04",
    "file": "/stickers/food/cake-04.svg",
    "keywords": [
      "food",
      "food",
      "อาหาร",
      "cake",
      "เค้ก"
    ]
  },
  {
    "id": "food-05",
    "category": "food",
    "name": "icecream-05",
    "file": "/stickers/food/icecream-05.svg",
    "keywords": [
      "food",
      "food",
      "อาหาร",
      "ice cream",
      "ไอติม",
      "ไอศกรีม"
    ]
  },
  {
    "id": "food-06",
    "category": "food",
    "name": "cake-06",
    "file": "/stickers/food/cake-06.svg",
    "keywords": [
      "food",
      "food",
      "อาหาร",
      "cake",
      "เค้ก"
    ]
  },
  {
    "id": "food-07",
    "category": "food",
    "name": "icecream-07",
    "file": "/stickers/food/icecream-07.svg",
    "keywords": [
      "food",
      "food",
      "อาหาร",
      "ice cream",
      "ไอติม",
      "ไอศกรีม"
    ]
  },
  {
    "id": "food-08",
    "category": "food",
    "name": "cake-08",
    "file": "/stickers/food/cake-08.svg",
    "keywords": [
      "food",
      "food",
      "อาหาร",
      "cake",
      "เค้ก"
    ]
  },
  {
    "id": "food-09",
    "category": "food",
    "name": "icecream-09",
    "file": "/stickers/food/icecream-09.svg",
    "keywords": [
      "food",
      "food",
      "อาหาร",
      "ice cream",
      "ไอติม",
      "ไอศกรีม"
    ]
  },
  {
    "id": "food-10",
    "category": "food",
    "name": "cake-10",
    "file": "/stickers/food/cake-10.svg",
    "keywords": [
      "food",
      "food",
      "อาหาร",
      "cake",
      "เค้ก"
    ]
  },
  {
    "id": "food-11",
    "category": "food",
    "name": "icecream-11",
    "file": "/stickers/food/icecream-11.svg",
    "keywords": [
      "food",
      "food",
      "อาหาร",
      "ice cream",
      "ไอติม",
      "ไอศกรีม"
    ]
  },
  {
    "id": "food-12",
    "category": "food",
    "name": "cake-12",
    "file": "/stickers/food/cake-12.svg",
    "keywords": [
      "food",
      "food",
      "อาหาร",
      "cake",
      "เค้ก"
    ]
  },
  {
    "id": "vehicles-01",
    "category": "vehicles",
    "name": "car-01",
    "file": "/stickers/vehicles/car-01.svg",
    "keywords": [
      "vehicles",
      "vehicles",
      "ยานพาหนะ",
      "car",
      "รถ"
    ]
  },
  {
    "id": "vehicles-02",
    "category": "vehicles",
    "name": "airplane-02",
    "file": "/stickers/vehicles/airplane-02.svg",
    "keywords": [
      "vehicles",
      "vehicles",
      "ยานพาหนะ",
      "airplane",
      "plane",
      "เครื่องบิน"
    ]
  },
  {
    "id": "vehicles-03",
    "category": "vehicles",
    "name": "car-03",
    "file": "/stickers/vehicles/car-03.svg",
    "keywords": [
      "vehicles",
      "vehicles",
      "ยานพาหนะ",
      "car",
      "รถ"
    ]
  },
  {
    "id": "vehicles-04",
    "category": "vehicles",
    "name": "airplane-04",
    "file": "/stickers/vehicles/airplane-04.svg",
    "keywords": [
      "vehicles",
      "vehicles",
      "ยานพาหนะ",
      "airplane",
      "plane",
      "เครื่องบิน"
    ]
  },
  {
    "id": "vehicles-05",
    "category": "vehicles",
    "name": "car-05",
    "file": "/stickers/vehicles/car-05.svg",
    "keywords": [
      "vehicles",
      "vehicles",
      "ยานพาหนะ",
      "car",
      "รถ"
    ]
  },
  {
    "id": "vehicles-06",
    "category": "vehicles",
    "name": "airplane-06",
    "file": "/stickers/vehicles/airplane-06.svg",
    "keywords": [
      "vehicles",
      "vehicles",
      "ยานพาหนะ",
      "airplane",
      "plane",
      "เครื่องบิน"
    ]
  },
  {
    "id": "vehicles-07",
    "category": "vehicles",
    "name": "car-07",
    "file": "/stickers/vehicles/car-07.svg",
    "keywords": [
      "vehicles",
      "vehicles",
      "ยานพาหนะ",
      "car",
      "รถ"
    ]
  },
  {
    "id": "vehicles-08",
    "category": "vehicles",
    "name": "airplane-08",
    "file": "/stickers/vehicles/airplane-08.svg",
    "keywords": [
      "vehicles",
      "vehicles",
      "ยานพาหนะ",
      "airplane",
      "plane",
      "เครื่องบิน"
    ]
  },
  {
    "id": "vehicles-09",
    "category": "vehicles",
    "name": "car-09",
    "file": "/stickers/vehicles/car-09.svg",
    "keywords": [
      "vehicles",
      "vehicles",
      "ยานพาหนะ",
      "car",
      "รถ"
    ]
  },
  {
    "id": "vehicles-10",
    "category": "vehicles",
    "name": "airplane-10",
    "file": "/stickers/vehicles/airplane-10.svg",
    "keywords": [
      "vehicles",
      "vehicles",
      "ยานพาหนะ",
      "airplane",
      "plane",
      "เครื่องบิน"
    ]
  },
  {
    "id": "vehicles-11",
    "category": "vehicles",
    "name": "car-11",
    "file": "/stickers/vehicles/car-11.svg",
    "keywords": [
      "vehicles",
      "vehicles",
      "ยานพาหนะ",
      "car",
      "รถ"
    ]
  },
  {
    "id": "vehicles-12",
    "category": "vehicles",
    "name": "airplane-12",
    "file": "/stickers/vehicles/airplane-12.svg",
    "keywords": [
      "vehicles",
      "vehicles",
      "ยานพาหนะ",
      "airplane",
      "plane",
      "เครื่องบิน"
    ]
  },
  {
    "id": "sports-01",
    "category": "sports",
    "name": "ball-01",
    "file": "/stickers/sports/ball-01.svg",
    "keywords": [
      "sports",
      "sports",
      "กีฬา",
      "ball",
      "ลูกบอล",
      "soccer"
    ]
  },
  {
    "id": "sports-02",
    "category": "sports",
    "name": "ball-02",
    "file": "/stickers/sports/ball-02.svg",
    "keywords": [
      "sports",
      "sports",
      "กีฬา",
      "ball",
      "ลูกบอล",
      "soccer"
    ]
  },
  {
    "id": "sports-03",
    "category": "sports",
    "name": "ball-03",
    "file": "/stickers/sports/ball-03.svg",
    "keywords": [
      "sports",
      "sports",
      "กีฬา",
      "ball",
      "ลูกบอล",
      "soccer"
    ]
  },
  {
    "id": "sports-04",
    "category": "sports",
    "name": "ball-04",
    "file": "/stickers/sports/ball-04.svg",
    "keywords": [
      "sports",
      "sports",
      "กีฬา",
      "ball",
      "ลูกบอล",
      "soccer"
    ]
  },
  {
    "id": "sports-05",
    "category": "sports",
    "name": "ball-05",
    "file": "/stickers/sports/ball-05.svg",
    "keywords": [
      "sports",
      "sports",
      "กีฬา",
      "ball",
      "ลูกบอล",
      "soccer"
    ]
  },
  {
    "id": "sports-06",
    "category": "sports",
    "name": "ball-06",
    "file": "/stickers/sports/ball-06.svg",
    "keywords": [
      "sports",
      "sports",
      "กีฬา",
      "ball",
      "ลูกบอล",
      "soccer"
    ]
  },
  {
    "id": "sports-07",
    "category": "sports",
    "name": "ball-07",
    "file": "/stickers/sports/ball-07.svg",
    "keywords": [
      "sports",
      "sports",
      "กีฬา",
      "ball",
      "ลูกบอล",
      "soccer"
    ]
  },
  {
    "id": "sports-08",
    "category": "sports",
    "name": "ball-08",
    "file": "/stickers/sports/ball-08.svg",
    "keywords": [
      "sports",
      "sports",
      "กีฬา",
      "ball",
      "ลูกบอล",
      "soccer"
    ]
  },
  {
    "id": "sports-09",
    "category": "sports",
    "name": "ball-09",
    "file": "/stickers/sports/ball-09.svg",
    "keywords": [
      "sports",
      "sports",
      "กีฬา",
      "ball",
      "ลูกบอล",
      "soccer"
    ]
  },
  {
    "id": "sports-10",
    "category": "sports",
    "name": "ball-10",
    "file": "/stickers/sports/ball-10.svg",
    "keywords": [
      "sports",
      "sports",
      "กีฬา",
      "ball",
      "ลูกบอล",
      "soccer"
    ]
  },
  {
    "id": "sports-11",
    "category": "sports",
    "name": "ball-11",
    "file": "/stickers/sports/ball-11.svg",
    "keywords": [
      "sports",
      "sports",
      "กีฬา",
      "ball",
      "ลูกบอล",
      "soccer"
    ]
  },
  {
    "id": "sports-12",
    "category": "sports",
    "name": "ball-12",
    "file": "/stickers/sports/ball-12.svg",
    "keywords": [
      "sports",
      "sports",
      "กีฬา",
      "ball",
      "ลูกบอล",
      "soccer"
    ]
  },
  {
    "id": "cute-01",
    "category": "cute",
    "name": "heart-01",
    "file": "/stickers/cute/heart-01.svg",
    "keywords": [
      "cute",
      "cute",
      "น่ารัก",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "cute-02",
    "category": "cute",
    "name": "smiley-02",
    "file": "/stickers/cute/smiley-02.svg",
    "keywords": [
      "cute",
      "cute",
      "น่ารัก",
      "smiley",
      "face",
      "หน้ายิ้ม"
    ]
  },
  {
    "id": "cute-03",
    "category": "cute",
    "name": "rainbow-03",
    "file": "/stickers/cute/rainbow-03.svg",
    "keywords": [
      "cute",
      "cute",
      "น่ารัก",
      "rainbow",
      "สายรุ้ง"
    ]
  },
  {
    "id": "cute-04",
    "category": "cute",
    "name": "heart-04",
    "file": "/stickers/cute/heart-04.svg",
    "keywords": [
      "cute",
      "cute",
      "น่ารัก",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "cute-05",
    "category": "cute",
    "name": "smiley-05",
    "file": "/stickers/cute/smiley-05.svg",
    "keywords": [
      "cute",
      "cute",
      "น่ารัก",
      "smiley",
      "face",
      "หน้ายิ้ม"
    ]
  },
  {
    "id": "cute-06",
    "category": "cute",
    "name": "rainbow-06",
    "file": "/stickers/cute/rainbow-06.svg",
    "keywords": [
      "cute",
      "cute",
      "น่ารัก",
      "rainbow",
      "สายรุ้ง"
    ]
  },
  {
    "id": "cute-07",
    "category": "cute",
    "name": "heart-07",
    "file": "/stickers/cute/heart-07.svg",
    "keywords": [
      "cute",
      "cute",
      "น่ารัก",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "cute-08",
    "category": "cute",
    "name": "smiley-08",
    "file": "/stickers/cute/smiley-08.svg",
    "keywords": [
      "cute",
      "cute",
      "น่ารัก",
      "smiley",
      "face",
      "หน้ายิ้ม"
    ]
  },
  {
    "id": "cute-09",
    "category": "cute",
    "name": "rainbow-09",
    "file": "/stickers/cute/rainbow-09.svg",
    "keywords": [
      "cute",
      "cute",
      "น่ารัก",
      "rainbow",
      "สายรุ้ง"
    ]
  },
  {
    "id": "cute-10",
    "category": "cute",
    "name": "heart-10",
    "file": "/stickers/cute/heart-10.svg",
    "keywords": [
      "cute",
      "cute",
      "น่ารัก",
      "love",
      "heart",
      "หัวใจ",
      "รัก"
    ]
  },
  {
    "id": "cute-11",
    "category": "cute",
    "name": "smiley-11",
    "file": "/stickers/cute/smiley-11.svg",
    "keywords": [
      "cute",
      "cute",
      "น่ารัก",
      "smiley",
      "face",
      "หน้ายิ้ม"
    ]
  },
  {
    "id": "cute-12",
    "category": "cute",
    "name": "rainbow-12",
    "file": "/stickers/cute/rainbow-12.svg",
    "keywords": [
      "cute",
      "cute",
      "น่ารัก",
      "rainbow",
      "สายรุ้ง"
    ]
  },
  {
    "id": "misc-01",
    "category": "misc",
    "name": "gem-01",
    "file": "/stickers/misc/gem-01.svg",
    "keywords": [
      "misc",
      "miscellaneous",
      "อื่นๆ",
      "gem",
      "diamond",
      "เพชร"
    ]
  },
  {
    "id": "misc-02",
    "category": "misc",
    "name": "crown-02",
    "file": "/stickers/misc/crown-02.svg",
    "keywords": [
      "misc",
      "miscellaneous",
      "อื่นๆ",
      "crown",
      "มงกุฎ"
    ]
  },
  {
    "id": "misc-03",
    "category": "misc",
    "name": "sparkle-03",
    "file": "/stickers/misc/sparkle-03.svg",
    "keywords": [
      "misc",
      "miscellaneous",
      "อื่นๆ",
      "sparkle",
      "shine",
      "ประกาย"
    ]
  },
  {
    "id": "misc-04",
    "category": "misc",
    "name": "moon-04",
    "file": "/stickers/misc/moon-04.svg",
    "keywords": [
      "misc",
      "miscellaneous",
      "อื่นๆ",
      "moon",
      "พระจันทร์"
    ]
  },
  {
    "id": "misc-05",
    "category": "misc",
    "name": "gem-05",
    "file": "/stickers/misc/gem-05.svg",
    "keywords": [
      "misc",
      "miscellaneous",
      "อื่นๆ",
      "gem",
      "diamond",
      "เพชร"
    ]
  },
  {
    "id": "misc-06",
    "category": "misc",
    "name": "crown-06",
    "file": "/stickers/misc/crown-06.svg",
    "keywords": [
      "misc",
      "miscellaneous",
      "อื่นๆ",
      "crown",
      "มงกุฎ"
    ]
  },
  {
    "id": "misc-07",
    "category": "misc",
    "name": "sparkle-07",
    "file": "/stickers/misc/sparkle-07.svg",
    "keywords": [
      "misc",
      "miscellaneous",
      "อื่นๆ",
      "sparkle",
      "shine",
      "ประกาย"
    ]
  },
  {
    "id": "misc-08",
    "category": "misc",
    "name": "moon-08",
    "file": "/stickers/misc/moon-08.svg",
    "keywords": [
      "misc",
      "miscellaneous",
      "อื่นๆ",
      "moon",
      "พระจันทร์"
    ]
  },
  {
    "id": "misc-09",
    "category": "misc",
    "name": "gem-09",
    "file": "/stickers/misc/gem-09.svg",
    "keywords": [
      "misc",
      "miscellaneous",
      "อื่นๆ",
      "gem",
      "diamond",
      "เพชร"
    ]
  },
  {
    "id": "misc-10",
    "category": "misc",
    "name": "crown-10",
    "file": "/stickers/misc/crown-10.svg",
    "keywords": [
      "misc",
      "miscellaneous",
      "อื่นๆ",
      "crown",
      "มงกุฎ"
    ]
  },
  {
    "id": "misc-11",
    "category": "misc",
    "name": "sparkle-11",
    "file": "/stickers/misc/sparkle-11.svg",
    "keywords": [
      "misc",
      "miscellaneous",
      "อื่นๆ",
      "sparkle",
      "shine",
      "ประกาย"
    ]
  },
  {
    "id": "misc-12",
    "category": "misc",
    "name": "moon-12",
    "file": "/stickers/misc/moon-12.svg",
    "keywords": [
      "misc",
      "miscellaneous",
      "อื่นๆ",
      "moon",
      "พระจันทร์"
    ]
  }
];
